name: Java CI/CD Pipeline TourGuide V2

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
      
    - name: Install GPSUtil Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/gpsUtil.jar \
          -DgroupId=gpsUtil \
          -DartifactId=gpsUtil \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: Install RewardCentral Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/RewardCentral.jar \
          -DgroupId=rewardCentral \
          -DartifactId=rewardCentral \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: Install TripPricer Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/TripPricer.jar \
          -DgroupId=tripPricer \
          -DartifactId=tripPricer \
          -Dversion=1.0.0 \
          -Dpackaging=jar


    - name: Compile
      run: mvn compile

  test:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
      
    - name: Install GPSUtil Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/gpsUtil.jar \
          -DgroupId=gpsUtil \
          -DartifactId=gpsUtil \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: Install RewardCentral Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/RewardCentral.jar \
          -DgroupId=rewardCentral \
          -DartifactId=rewardCentral \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: Install TripPricer Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/TripPricer.jar \
          -DgroupId=tripPricer \
          -DartifactId=tripPricer \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: test
      run: mvn test


  package:
    runs-on: ubuntu-latest 
    
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
      
    - name: Install GPSUtil Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/gpsUtil.jar \
          -DgroupId=gpsUtil \
          -DartifactId=gpsUtil \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: Install RewardCentral Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/RewardCentral.jar \
          -DgroupId=rewardCentral \
          -DartifactId=rewardCentral \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: Install TripPricer Library
      run: |
        mvn install:install-file \
          -Dfile=./libs/TripPricer.jar \
          -DgroupId=tripPricer \
          -DartifactId=tripPricer \
          -Dversion=1.0.0 \
          -Dpackaging=jar


    - name: Package
      run: mvn package
